In [2]:
import gym
import keras
import numpy as np

In [50]:
# create env
env = gym.make('CartPole-v1')
env.reset()

array([ 0.00970524, -0.03259068, -0.00368581,  0.00753249])

In [16]:
env.action_space, env.observation_space

(Discrete(2), Box(4,))

In [17]:
env.observation_space.low, env.observation_space.high 

(array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
       dtype=float32),
 array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
       dtype=float32))

In [57]:
def create_buckets(low, high, num_buckets):
    range_ = high - low
    bucket_width = range_ / num_buckets
    return [(ii)*bucket_width for ii in range(num_buckets)]

In [58]:
create_buckets(-10, 10, 3)

[0.0, 6.666666666666667, 13.333333333333334]